### ISSUE TITLE
Specific CSS broken after vulcanizing

### ISSUE THREAD

**Issue by omarbelkhodja** [PolymerLabs/polybuild#21]
I'm using polybuild to vulcanize my app, before deploying on the webserver. My website is using a Polymer paper-dialog that uses the following CSS code:

```
.shadow-elevation-16dp {
  box-shadow: 0 16px 24px 2px rgba(0, 0, 0, 0.14),
              0  6px 30px 5px rgba(0, 0, 0, 0.12),
              0  8px 10px -5px rgba(0, 0, 0, 0.4);
}
```

After vulcanizing, this code is transformed into the following:

```
.shadow-elevation-16dp {box-shadow: 0 16px 24px 2px rgba(0, 0, 0, 0.14),06px 30px 5px rgba(0, 0, 0, 0.12),08px 10px -5px rgba(0, 0, 0, 0.4);}
```

There are some missing spaces, (see 06px instead of 0 6px, and 08px instead of 0 8px).

Of course, this is leading to shadows not displayed.

**Comment by ebidel** [comment]
https://github.com/PolymerLabs/polyclean/blob/master/index.js#L144 looks like it blindly removes 2 or more spaces, which would explain your example.

**Comment by ebidel** [comment]
I'm going to move this to polyclean.

**Comment by ebidel** [comment]
This issue was moved to PolymerLabs/polyclean#8
