### ISSUE TITLE
Polybuild breaks @apply rules

### ISSUE THREAD

**Issue by ebidel** [PolymerLabs/polybuild#22]
_From @vaadin-marcus on December 2, 2015 23:7_

After running the dist target with PSK, it seems that any @apply mixins get broken. polymer#1.2.3

Below is an example: 

Running with `gulp serve`
<img width="439" alt="apply-normal" src="https://cloud.githubusercontent.com/assets/883698/11547037/dac80130-9905-11e5-90e0-83aa5f70179b.png">

Running with `gulp serve:dist`
<img width="393" alt="apply-polybuild" src="https://cloud.githubusercontent.com/assets/883698/11547039/dcc5a500-9905-11e5-9e71-e7289d57ad1f.png">

_Copied from original issue: Polymer/polymer#3126_

**Comment by marcushellberg** [comment]
I did some further digging around to figure out what's going on. 

It seems like the build only breaks mixins that include other mixins. So, `@apply(--layout-vertical)` will produce `at-rule,` in the built CSS file. Mixins that do not include other mixins seem to work correctly, so for instance `@apply(--layout-flex)` will produce the correct output. 

Hope that helps

**Comment by marcushellberg** [comment]
Related: https://github.com/PolymerElements/iron-flex-layout/issues/60

**Comment by justinfagnani** [comment]
Looks like it's fixed in https://github.com/jakubpawlowicz/clean-css/issues/714
