### ISSUE TITLE
Specify name output.

### ISSUE THREAD

**Issue by indolering** [PolymerLabs/polybuild#5]
Currently, the tool appends "build" to the names of the files.  I would like to be able to specify this setting manually.

Not sure if we need to just add documentation or actually support it.

**Comment by isaldarriaga** [comment]
+1

**Comment by arturparkhisenko** [comment]
:+1:

**Comment by addyosmani** [comment]
Imo, configuration over this would be useful. I do think `polybuild` intends to be somewhat opinionated however, but :+1: otherwise.

**Comment by indolering** [comment]
The impetus behind this request is that the name change breaks my functional tests.  I can rename the output files, but I think polybuild should just respect my naming conventions.

**Comment by Westbrook** [comment]
:+1:

**Comment by indolering** [comment]
Resolved in aforementioned merge.
